FROM ubi8/ubi:8.5
MAINTAINER amirhmzh <amirhmzh@hotmail.com>

ARG NEXUS_VERSION=2.14.3-02
ENV NEXUS_HOME=/opt/nexus

RUN yum install java-1.8.0-openjdk-devel -y && yum clean all

RUN groupadd -r nexus -f -g 1001 && useradd -u 1001 -r -g nexus -m -d ${NEXUS_HOME} -s /sbin/nologin \
	-c "Nexus User" nexus && chown -R nexus:nexus ${NEXUS_HOME} && chmod -R 755 ${NEXUS_HOME}

ADD nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}

RUN ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2

USER nexus

WORKDIR /opt/nexus

VOLUME /opt/nexus/sonatype-work

COPY nexus-start.sh /opt/nexus

CMD ["/opt/nexus/nexus-start.sh"]
